import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,joinGame,startGame,act,advanceBots,advanceIdle,playerByToken,score,scoreByEra,publicView,voiceMessage} from '../web/game.js';
import {deckFor,ERAS} from '../web/catalog.js';

function seeded(seed){let n=seed>>>0;return ()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;};}
function setup(count=3,rng=seeded(3)){const g=createGame('甲',rng);for(let i=1;i<count;i++)joinGame(g,`玩家${i+1}`);startGame(g,g.players[0]);return g;}
function beginAuction(g){for(const p of g.players)if(!g.ready[p.id])act(g,p,{kind:'ready'});act(g,g.players[g.host],{kind:'beginAuction'});}
function inventory(g){const cards=[...g.deck,...g.discard,...g.bank,...g.selection.filter(Boolean),...g.players.flatMap(p=>p.hand)];assert.equal(cards.length,g.eras.length*9-1);assert.equal(new Set(cards.map(c=>c.id)).size,cards.length);}
function step(g){const h=g.players[g.host],a=g.auction;
 switch(g.phase){
  case 'select':act(g,h,{kind:'choose',position:0,mode:'open',direction:g.direction??1});break;
  case 'pre-auction':beginAuction(g);break;
  case 'open':{const p=g.players.find(x=>x.id===a.order[a.actorIndex]);act(g,p,{kind:'pass'});break;}
  case 'sealed':{const p=g.players.find(x=>a.bidders.includes(x.id)&&!Object.hasOwn(a.offers,x.id));act(g,p,{kind:'sealedBid',amount:0});break;}
  case 'trade-request':act(g,h,{kind:'skipRequest'});break;
  case 'trade-free':act(g,h,{kind:'skipTrade'});break;
  case 'turn-end':act(g,h,{kind:'next'});break;
  default:throw Error(`意外阶段 ${g.phase}`);
 }
}

test('九个时代共 81 张卡，各时代数量正确',()=>{const all=deckFor(ERAS.map(e=>e[0]));assert.equal(all.length,81);assert.equal(new Set(all.map(c=>c.id)).size,81);for(const [era] of ERAS)assert.deepEqual([1,2,3,4].map(n=>all.filter(c=>c.era===era&&c.star===n).length),[3,3,2,1]);});
test('3–6 人均为 2N 轮，每轮 N−1 张，牌数守恒',()=>{for(let count=3;count<=6;count++){const g=setup(count);assert.equal(g.maxTurns,count*2);assert.equal(g.selection.length,count-1);let steps=0;while(g.phase!=='finished'&&steps++<1000){step(g);inventory(g);}assert.ok(steps<1000);assert.equal(g.turn,count*2);assert.equal(g.winner.length,count);}});
test('盲标只见卡背，拍卖后才进入私下交易',()=>{const g=setup(),h=g.players[g.host];assert.equal(publicView(g,h).selection[0].name,undefined);assert.equal(publicView(g,null).selection.length,2);act(g,h,{kind:'choose',position:0,mode:'sealed',direction:1});assert.equal(g.phase,'pre-auction');assert.equal(publicView(g,h).currentLot,undefined);beginAuction(g);assert.equal(g.phase,'sealed');for(const p of g.players)act(g,p,{kind:'sealedBid',amount:0});assert.equal(g.phase,'pre-auction');beginAuction(g);for(const p of g.players.filter(x=>x.id!==g.players[g.host].id))act(g,p,{kind:'pass'});if(g.phase==='open')act(g,h,{kind:'pass'});assert.equal(g.phase,'trade-request');});
test('选择第二张心仪卡后移至首拍，首张享八折',()=>{const g=setup(),h=g.players[g.host],chosen=g.selection[1].id,other=g.selection[0].id;g.rng=()=>0;act(g,h,{kind:'choose',position:1,mode:'sealed',direction:1});assert.equal(g.selection[0].id,chosen);assert.equal(g.selection[1].id,other);assert.equal(g.blindPosition,0);beginAuction(g);assert.equal(g.auction.card.id,chosen);assert.equal(publicView(g,h).blindPosition,0);const star=g.auction.card.star;for(const p of g.players)act(g,p,{kind:'sealedBid',amount:p.id===h.id?20:0});assert.equal(g.lastSettlement.discount,true);assert.equal(g.lastSettlement.total,Math.ceil((20+star)*.8));});
test('拍前准备可撤回，撤回后可继续出售',()=>{const g=setup(),h=g.players[g.host],c=deckFor(['汉'])[0];g.deck=g.deck.filter(x=>x.id!==c.id);h.hand.push(c);act(g,h,{kind:'choose',position:0,mode:'open',direction:1});act(g,h,{kind:'ready'});assert.throws(()=>act(g,h,{kind:'bankSell',card:c.id}),/已结束/);act(g,h,{kind:'unready'});assert.equal(g.ready[h.id],undefined);act(g,h,{kind:'bankSell',card:c.id});assert.ok(g.bank.some(x=>x.id===c.id));});
test('暗拍最高价并列，重拍三次仍同则流拍',()=>{const g=setup(),h=g.players[g.host];act(g,h,{kind:'choose',position:0,mode:'sealed',direction:1});beginAuction(g);const c=g.auction.card;for(let round=0;round<4;round++){const bidders=[...g.auction.bidders];for(const pid of bidders)act(g,g.players.find(p=>p.id===pid),{kind:'sealedBid',amount:1});}assert.equal(g.phase,'pre-auction');assert.ok(g.discard.some(x=>x.id===c.id));});
test('骰子修正只投一次；首名超支受罚，次名同骰接手',()=>{const g=setup(3),h=g.players[g.host];g.rng=()=>0;act(g,h,{kind:'choose',position:0,mode:'sealed',direction:1});beginAuction(g);const a=g.auction,first=g.players.find(p=>p.id!==h.id),other=g.players.find(p=>p.id!==h.id&&p.id!==first.id);first.coins=1;act(g,first,{kind:'sealedBid',amount:1});act(g,other,{kind:'sealedBid',amount:0});act(g,h,{kind:'sealedBid',amount:0});assert.equal(first.banRemaining,2);assert.equal(g.phase,'pre-auction');assert.ok(g.discard.some(c=>c.id===a.card.id));});
test('拍卖行每张翻面前可多次出售，红卡按成交价扣 20% 税',()=>{const g=setup(),h=g.players[g.host],c=deckFor(['汉']).find(x=>x.red);h.hand.push(c);g.deck=g.deck.filter(x=>x.id!==c.id);act(g,h,{kind:'choose',position:0,mode:'open',direction:1});const before=h.coins,rate=100+g.rates[4];act(g,h,{kind:'bankSell',card:c.id});assert.equal(h.coins-before,Math.floor(40*rate/100)-Math.ceil(Math.floor(40*rate/100)*.2));assert.equal(g.rates[4],rate-110);assert.ok(g.bank.some(x=>x.id===c.id));});
test('同系 123 与 1234 计分，孤立红卡只没收自身估值',()=>{const d=deckFor(['汉']);const p={coins:17,hand:d.filter(c=>c.star<=3||c.red)};assert.deepEqual(score(p),{coins:17,value:380,penalty:0,total:397,full:1});p.hand=d.filter(c=>c.star===2||c.red);assert.deepEqual(score(p),{coins:17,value:100,penalty:40,total:77,full:0});});
test('逐时代计分与总分一致，且仅向持有人展示当前藏品',()=>{const g=setup(),p=g.players[0],c=deckFor(['汉']).filter(x=>x.star===1||x.red);p.hand.push(...c);const parts=scoreByEra(p),own=publicView(g,p),other=publicView(g,g.players[1]);assert.equal(parts.reduce((sum,x)=>sum+x.net,0),score(p).value-score(p).penalty);assert.equal(own.me.byEra.find(x=>x.era==='汉').stars.length,1);assert.equal(other.me.byEra.some(x=>x.era==='汉'),false);assert.equal(other.players[0].hand,undefined);});
test('成交结算单公开骰点与实付，保留暗拍揭晓前的报价秘密',()=>{const g=setup(),h=g.players[g.host];g.rng=()=>0;act(g,h,{kind:'choose',position:0,mode:'sealed',direction:1});beginAuction(g);const c=g.auction.card;assert.equal(publicView(g,h).lastSettlement,null);const coins=h.coins;for(const p of g.players)act(g,p,{kind:'sealedBid',amount:p.id===h.id?20:0});const receipt=publicView(g,null).lastSettlement;assert.equal(receipt.card,c.name);assert.equal(receipt.roll,1);assert.equal(receipt.winner,h.name);assert.equal(receipt.bid,20);assert.equal(receipt.total,coins-h.coins);});
test('等待超时后托管并允许玩家接管',()=>{const g=setup(),h=g.players[g.host];assert.equal(advanceIdle(g,1000),true);assert.equal(g.idle.deadline,91000);assert.equal(advanceIdle(g,90999),false);assert.equal(advanceIdle(g,91000),true);assert.equal(h.idlePilot,true);assert.equal(publicView(g,h).me.idlePilot,true);act(g,h,{kind:'resume'});assert.equal(h.idlePilot,false);assert.equal(advanceIdle(g,92000),true);assert.ok(g.idle.deadline>92000);});
test('私下求购成功，没成功才可自由交易',()=>{const g=setup(),h=g.players[g.host],seller=g.players.find(p=>p.id!==h.id),other=g.players.find(p=>p.id!==h.id&&p.id!==seller.id),c=deckFor(['汉'])[0];seller.hand=[c];g.phase='trade-request';act(g,h,{kind:'request',wanted:c.name,coins:10});act(g,seller,{kind:'respondRequest',card:c.id});act(g,other,{kind:'respondRequest'});assert.equal(g.phase,'request-choice');act(g,h,{kind:'chooseRequest',target:seller.id});assert.equal(g.phase,'turn-end');assert.ok(h.hand.some(x=>x.id===c.id));});
test('机器人与真人组合可以走完整局',()=>{for(let bots=2;bots<=5;bots++)for(let seed=1;seed<=20;seed++){const g=createGame('真人',seeded(seed+bots*100));const human=g.players[0];act(g,human,{kind:'setBots',count:bots});act(g,human,{kind:'start'});advanceBots(g);let steps=0;while(g.phase!=='finished'&&steps++<1500){const a=g.auction;if(g.phase==='select')act(g,human,{kind:'choose',position:0,mode:'open',direction:g.direction??1});else if(g.phase==='pre-auction'&&!g.ready[human.id])act(g,human,{kind:'ready'});else if(g.phase==='pre-auction'&&g.players[g.host].id===human.id)act(g,human,{kind:'beginAuction'});else if(g.phase==='open')act(g,human,{kind:'pass'});else if(g.phase==='sealed')act(g,human,{kind:'sealedBid',amount:0});else if(g.phase==='trade-request')act(g,human,{kind:'skipRequest'});else if(g.phase==='request-response')act(g,human,{kind:'respondRequest'});else if(g.phase==='request-choice')act(g,human,{kind:'chooseRequest'});else if(g.phase==='trade-free')act(g,human,{kind:'skipTrade'});else if(g.phase==='trade-response')act(g,human,{kind:'respondTrade',accept:false});else if(g.phase==='turn-end')act(g,human,{kind:'next'});else throw Error(`停在 ${g.phase}`);advanceBots(g);inventory(g);}assert.ok(steps<1500);assert.equal(g.phase,'finished');}});
test('机器人令牌不能作为真人身份登录',()=>{const g=createGame('真人');act(g,g.players[0],{kind:'setBots',count:2});assert.equal(playerByToken(g,g.players[1].token),undefined);});
test('观众可选座位，房主可安排机器人，开局后座位锁定',()=>{const g=createGame('房主'),owner=g.players[0],guest=joinGame(g,'观众',{spectate:true,avatar:'🐼'});assert.equal(publicView(g,guest).me.seat,null);assert.equal(g.players.length,1);act(g,guest,{kind:'sit',seat:4});assert.equal(g.players[1].id,guest.id);assert.equal(guest.avatar,'🐼');act(g,guest,{kind:'stand'});assert.equal(g.spectators[0].id,guest.id);act(g,owner,{kind:'setSeatBot',seat:4});assert.ok(g.players.some(p=>p.seat===4&&p.isBot));assert.throws(()=>act(g,guest,{kind:'sit',seat:4}),/已有人/);act(g,owner,{kind:'setSeatBot',seat:4});act(g,guest,{kind:'sit',seat:4});act(g,owner,{kind:'setSeatBot',seat:2});act(g,owner,{kind:'start'});assert.equal(g.maxTurns,6);assert.throws(()=>act(g,guest,{kind:'stand'}),/不能离开座位/);const late=joinGame(g,'晚到观众',{spectate:true});assert.equal(publicView(g,late).me.seat,null);assert.throws(()=>act(g,late,{kind:'choose',position:0,mode:'open'}),/旁观者不能操作/);});
test('围桌文字和语音可由观众发送，公开视图不暴露录音内容',()=>{const g=createGame('房主'),watcher=joinGame(g,'观众',{spectate:true}),audio=Buffer.alloc(90,7).toString('base64');act(g,watcher,{kind:'chatText',text:'第一张会是什么？'});act(g,watcher,{kind:'chatVoice',audio,mime:'audio/webm',duration:2});const view=publicView(g,null);assert.equal(view.chat[0].text,'第一张会是什么？');assert.equal(view.chat[1].kind,'voice');assert.equal(view.chat[1].audio,undefined);assert.equal(voiceMessage(g,view.chat[1].id).audio,audio);assert.throws(()=>act(g,watcher,{kind:'chatVoice',audio,mime:'text/plain',duration:2}),/格式无效/);});
